name: Java CI with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    # Check out the code from the repository
    - uses: actions/checkout@v4

    # Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # Build the project with Maven
    - name: Build with Maven
      run: mvn -B package --file trademate/pom.xml

    # Optional: Enable verbose logging for Maven
    # This can help with diagnosing any issues during the build
    # - name: Build with Maven (Verbose)
    #   run: mvn -B package --file trademate/pom.xml -X

    # Optional: Uploads the full dependency graph to GitHub
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
